"""empty message

Revision ID: 18b0d4977567
Revises: 4c31ff1b1fbd
Create Date: 2024-11-28 17:48:45.833562

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18b0d4977567'
down_revision = '4c31ff1b1fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('tool_call_name', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('icon', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('description', sa.Text(), server_default=sa.text("''::text"), nullable=False),
                    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('draft_graph', postgresql.JSONB(astext_type=sa.Text()),
                              server_default=sa.text("'{}'::jsonb"), nullable=False),
                    sa.Column('is_debug_passed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('published_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_workflow_id')
                    )
    op.create_table('workflow_result',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=True),
                    sa.Column('account_id', sa.UUID(), nullable=False),
                    sa.Column('workflow_id', sa.UUID(), nullable=False),
                    sa.Column('graph', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"),
                              nullable=False),
                    sa.Column('latency', sa.Float(), server_default=sa.text('0.0'), nullable=False),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_workflow_result_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_result')
    op.drop_table('workflow')
    # ### end Alembic commands ###
