"""empty message

Revision ID: 36c79303c825
Revises: 775e752e0220
Create Date: 2025-01-01 22:31:42.281145

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '36c79303c825'
down_revision = '775e752e0220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index('account_email_idx', ['email'], unique=False)

    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.create_index('account_oauth_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('account_oauth_openid_provider_idx', ['openid', 'provider'], unique=False)

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index('api_key_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_key_api_key_idx', ['api_key'], unique=False)

    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.create_index('api_tool_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('api_tool_provider_id_name_idx', ['provider_id', 'name'], unique=False)

    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.create_index('api_tool_name_idx', ['name'], unique=False)
        batch_op.create_index('api_tool_provider_account_id_idx', ['account_id'], unique=False)

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.create_index('app_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('app_token_idx', ['token'], unique=False)

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.create_index('app_config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.create_index('app_config_version_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.create_index('app_dataset_join_app_id_dataset_id_idx', ['app_id', 'dataset_id'], unique=False)

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index('conversation_app_created_by_idx', ['created_by'], unique=False)
        batch_op.create_index('conversation_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.create_index('dataset_account_id_name_idx', ['account_id', 'name'], unique=False)

    with op.batch_alter_table('dataset_query', schema=None) as batch_op:
        batch_op.create_index('dataset_created_by_idx', ['created_by'], unique=False)
        batch_op.create_index('dataset_query_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('dataset_source_app_id_idx', ['source_app_id'], unique=False)

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('document_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('document_batch_idx', ['batch'], unique=False)
        batch_op.create_index('document_dataset_id_idx', ['dataset_id'], unique=False)

    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index('end_user_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('end_user_tenant_id_idx', ['tenant_id'], unique=False)

    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.create_index('keyword_table_dataset_id_idx', ['dataset_id'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index('message_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_created_by_idx', ['created_by'], unique=False)

    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.create_index('message_agent_thought_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('message_agent_thought_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('message_agent_thought_message_id_idx', ['message_id'], unique=False)

    with op.batch_alter_table('process_rule', schema=None) as batch_op:
        batch_op.create_index('process_rule_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('process_rule_dataset_id_idx', ['dataset_id'], unique=False)

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.create_index('segment_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('segment_dataset_id_idx', ['dataset_id'], unique=False)
        batch_op.create_index('segment_document_id_idx', ['document_id'], unique=False)

    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.create_index('upload_file_account_id_idx', ['account_id'], unique=False)

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.create_index('workflow_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_tool_call_name_idx', ['tool_call_name'], unique=False)

    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.create_index('workflow_result_account_id_idx', ['account_id'], unique=False)
        batch_op.create_index('workflow_result_app_id_idx', ['app_id'], unique=False)
        batch_op.create_index('workflow_result_workflow_id_idx', ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_result', schema=None) as batch_op:
        batch_op.drop_index('workflow_result_workflow_id_idx')
        batch_op.drop_index('workflow_result_app_id_idx')
        batch_op.drop_index('workflow_result_account_id_idx')

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_index('workflow_tool_call_name_idx')
        batch_op.drop_index('workflow_account_id_idx')

    with op.batch_alter_table('upload_file', schema=None) as batch_op:
        batch_op.drop_index('upload_file_account_id_idx')

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_index('segment_document_id_idx')
        batch_op.drop_index('segment_dataset_id_idx')
        batch_op.drop_index('segment_account_id_idx')

    with op.batch_alter_table('process_rule', schema=None) as batch_op:
        batch_op.drop_index('process_rule_dataset_id_idx')
        batch_op.drop_index('process_rule_account_id_idx')

    with op.batch_alter_table('message_agent_thought', schema=None) as batch_op:
        batch_op.drop_index('message_agent_thought_message_id_idx')
        batch_op.drop_index('message_agent_thought_conversation_id_idx')
        batch_op.drop_index('message_agent_thought_app_id_idx')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('message_created_by_idx')
        batch_op.drop_index('message_conversation_id_idx')

    with op.batch_alter_table('keyword_table', schema=None) as batch_op:
        batch_op.drop_index('keyword_table_dataset_id_idx')

    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index('end_user_tenant_id_idx')
        batch_op.drop_index('end_user_app_id_idx')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('document_dataset_id_idx')
        batch_op.drop_index('document_batch_idx')
        batch_op.drop_index('document_account_id_idx')

    with op.batch_alter_table('dataset_query', schema=None) as batch_op:
        batch_op.drop_index('dataset_source_app_id_idx')
        batch_op.drop_index('dataset_query_dataset_id_idx')
        batch_op.drop_index('dataset_created_by_idx')

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.drop_index('dataset_account_id_name_idx')

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index('conversation_app_id_idx')
        batch_op.drop_index('conversation_app_created_by_idx')

    with op.batch_alter_table('app_dataset_join', schema=None) as batch_op:
        batch_op.drop_index('app_dataset_join_app_id_dataset_id_idx')

    with op.batch_alter_table('app_config_version', schema=None) as batch_op:
        batch_op.drop_index('app_config_version_app_id_idx')

    with op.batch_alter_table('app_config', schema=None) as batch_op:
        batch_op.drop_index('app_config_app_id_idx')

    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_index('app_token_idx')
        batch_op.drop_index('app_account_id_idx')

    with op.batch_alter_table('api_tool_provider', schema=None) as batch_op:
        batch_op.drop_index('api_tool_provider_account_id_idx')
        batch_op.drop_index('api_tool_name_idx')

    with op.batch_alter_table('api_tool', schema=None) as batch_op:
        batch_op.drop_index('api_tool_provider_id_name_idx')
        batch_op.drop_index('api_tool_account_id_idx')

    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index('api_key_api_key_idx')
        batch_op.drop_index('api_key_account_id_idx')

    with op.batch_alter_table('account_oauth', schema=None) as batch_op:
        batch_op.drop_index('account_oauth_openid_provider_idx')
        batch_op.drop_index('account_oauth_account_id_idx')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index('account_email_idx')

    # ### end Alembic commands ###
