"""empty message

Revision ID: 775e752e0220
Revises: a5086d2a507c
Create Date: 2024-12-10 16:15:48.226829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '775e752e0220'
down_revision = 'a5086d2a507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('token', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
