"""empty message

Revision ID: b017b44df199
Revises: 493395dc50b8
Create Date: 2025-01-19 16:29:19.675947

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b017b44df199'
down_revision = '493395dc50b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_config',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('wechat_app_id', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=True),
                    sa.Column('wechat_app_secret', sa.String(length=255),
                              server_default=sa.text("''::character varying"), nullable=True),
                    sa.Column('wechat_token', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=True),
                    sa.Column('status', sa.String(length=255), server_default=sa.text("''::character varying"),
                              nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_wechat_config_id')
                    )
    with op.batch_alter_table('wechat_config', schema=None) as batch_op:
        batch_op.create_index('wechat_config_app_id_idx', ['app_id'], unique=False)

    op.create_table('wechat_end_user',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('openid', sa.String(), nullable=False),
                    sa.Column('app_id', sa.UUID(), nullable=False),
                    sa.Column('end_user_id', sa.UUID(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_wechat_end_user_id')
                    )
    with op.batch_alter_table('wechat_end_user', schema=None) as batch_op:
        batch_op.create_index('wechat_end_user_openid_app_id_idx', ['openid', 'app_id'], unique=False)

    op.create_table('wechat_message',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
                    sa.Column('wechat_end_user_id', sa.UUID(), nullable=False),
                    sa.Column('message_id', sa.UUID(), nullable=False),
                    sa.Column('is_pushed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_wechat_message_id')
                    )
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.create_index('wechat_message_wechat_end_user_id_idx', ['wechat_end_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_message', schema=None) as batch_op:
        batch_op.drop_index('wechat_message_wechat_end_user_id_idx')

    op.drop_table('wechat_message')
    with op.batch_alter_table('wechat_end_user', schema=None) as batch_op:
        batch_op.drop_index('wechat_end_user_openid_app_id_idx')

    op.drop_table('wechat_end_user')
    with op.batch_alter_table('wechat_config', schema=None) as batch_op:
        batch_op.drop_index('wechat_config_app_id_idx')

    op.drop_table('wechat_config')
    # ### end Alembic commands ###
